# Stage 1: Production Runner
# This starts from a lean, secure base image.
FROM node:18-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production

# We only copy the final, essential files needed to RUN the application.
# These files will be pre-generated by our CI/CD build step.
COPY dist ./dist
COPY node_modules ./node_modules
COPY package.json ./package.json

EXPOSE 5000

CMD ["npm", "start"]

CMD ["npm", "start"]